version: 2

updates:
  # CLI package dependencies
  - package-ecosystem: npm
    directory: packages/cli
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: /
      prefix: cli
    open-pull-requests-limit: 5
    target-branch: main

  # SDK package dependencies
  - package-ecosystem: npm
    directory: packages/sdk
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: /
      prefix: sdk
    open-pull-requests-limit: 5
    target-branch: main

  # Skills package dependencies
  - package-ecosystem: npm
    directory: packages/skills
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: /
      prefix: skills
    open-pull-requests-limit: 5
    target-branch: main

  # GitHub Actions workflows
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    target-branch: main
